Remove excessive import
Under the javac shipped in RHEL 7, we see the following error when
building the test suite:

jss/org/mozilla/jss/tests/TestBufferPRFD.java:8: error: package org.mozilla.jss.pkix does not exist
import org.mozilla.jss.pkix.*;
^

This is because the org.mozilla.jss.pkix namespace doesn't include any
classes; it only contains sub-packages.

Signed-off-by: Alexander Scheel <ascheel@redhat.com>